### PR TITLE
Set fullsweep_after on device channel

### PR DESCRIPTION
**Pull request by oestrich**
Remove drainer since it seems to be in the wrong spot and there's a default for it anyways

### CODE REVIEW

**Comment by joshk** [comment]
has this change been tested on your setup? were their any noticeable improvements?

also, why do you think the drainer is in the wrong spot?

**Comment by oestrich** [comment]
This has been tested with 1 device thus far. I suspect the drainer is in the wrong spot because of the docs, they say it should be at the same level as `websocket` and not nested below. 

In production like load tests we hang on to about 200KB per device, which is mostly garbage waiting to be collected. In local profiling with the one device we go from 40KB-60KB to ~5KB in the socket process. This is following the guide from Phoenix here https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#socket/3-websocket-configuration

**Comment by fhunleth** [comment]
Could the PR be split? The drainer one seems like it could be verified and merged independent of the GC change.

**Comment by joshk** [comment]
Interesting on both accounts.

I'm just triple checking with Mr Bandit if `drainer` is supported by Bandit, as the docs only mention Cowboy support.

Could you also remove the `drainer` config from the `endpoint.ex` file (its also defined there)

**Comment by oestrich** [comment]
PR is split and this is pointed at #1311 as a base

**Comment by joshk** [comment]
should we also set it here? https://github.com/nerves-hub/nerves_hub_web/blob/main/lib/nerves_hub_web/endpoint.ex#L19-L31

**Review by joshk — APPROVED** [review]
seems good to try out

**Pull request merged**
