### PR TITLE
Remove device health column from devices index table

### PR DESCRIPTION
**Pull request by coryjewell**
### Why
- Remove health column and make it more visibly impactful when a device is quarantined. Quarantine status will now display in the ID column. User is still able to filter by device health if desired.

### How
- Removed health column, updated quarantined badge to show quarantine icon
- Updated quarantine icon to be consistent on the index page and two places on the show page (Previously the Quarantine button on the show page was using a different icon)
- Removed extra delete button on device show page

### CODE REVIEW

**Review by jjcarstens — APPROVED** [review]

**Comment by mobileoverlord** [comment]
This was merged into main

**Comment by coryjewell** [comment]
@mobileoverlord It doesn't look like this was actually merged into main?

**Comment by mobileoverlord** [comment]
It looks like another branch had it in. https://github.com/nerves-hub/nerves_hub_web/commit/db74e3b42a73e0b43c9f5112302bf6e9164c14b4

I tried to rebase this from main and ff, but it was "already complete"

**Comment by mobileoverlord** [comment]
Oh I see, it was followed by a revert and not rebased out. :/ I'll try to merge it manually.

**Comment by oantila** [comment]
@mobileoverlord is there anything preventing to get this merged? Was hoping we can push it through.

**Comment by mobileoverlord** [comment]
Okay. _now_ this was cherry picked into main.

**Pull request closed without merging**
