### PR TITLE
Improve Deployment index screen and related dialogs

### PR DESCRIPTION
**Pull request by stwf**

### CODE REVIEW

**Comment by stwf** [comment]
screen shot 2018-08-29 at 10 11 43 pm

**Comment by stwf** [comment]
screen shot 2018-08-29 at 10 12 01 pm

**Comment by stwf** [comment]
Cleaned up the deployments page as well as some of the associated dialogs.

**Comment by stwf** [comment]
addresses ticket:
https://github.com/nerves-hub/nerves_hub_web/issues/207

**Comment by mobileoverlord** [comment]
Thanks, this looks great. I added flex box to the table to enforce your `col-x` layouts and updated the style a little to make it match the `ul` on the product page. ❤️ Thanks!

**Pull request merged**
