### PR TITLE
Device certificate fixes

### PR DESCRIPTION
**Pull request by elinol**
Fixes bug where certificates could not be downloaded due to certificates not preloaded on device. (https://github.com/nerves-hub/nerves_hub_web/issues/1532)

Also fixes certificate upload bug (discovered when trying to reproduce the download bug) by adding phx-change handler to live upload. This is required for uploads to work. For now it only does `{:noreply, socket}`, maybe not optimal but we can discuss proper validation later on if wanted.

### CODE REVIEW

**Comment by joshk** [comment]
Awesome find and fix!

I'm surprised that we didn't have a test failure for this, were you able to replicate this in a test?

**Comment by elinol** [comment]
There are no tests for this yet, I'll go ahead and add some. Would you prefer it in a separate PR on included here?

**Comment by joshk** [comment]
Same PR, please. I really appreciate it.

**Comment by elinol** [comment]
Added tests for certificate download (in controller only) and upload via device settings liveview. My ambition was to write liveview tests for download and deleting certificates, but haven't manage to toggle the options dropdown within the test flow, I think perhaps the view has to be rewritten a bit for that to work.

**Review by joshk — APPROVED** [review]
Awesome work!

**Pull request merged**
