### PR TITLE
Default delta updater can delta non-block resources

### LINKED ISSUE #885: Add support for FAT resources delta updates
Once fwup supports FAT resources delta updates  (see https://github.com/fwup-home/fwup/pull/202), default DeltaUpdater should be able to create compatible delta updates, whenever fwup version matches.

### PR DESCRIPTION
**Pull request by jeanparpaillon**
Requires fwup >= 1.10.0

Closes #885

### CODE REVIEW

**Comment by jeanparpaillon** [comment]
See https://github.com/fwup-home/fwup/pull/202 for fwup related PR
Minimal version may change depending on fwup next release

**Comment by jeanparpaillon** [comment]
@fhunleth thanks for the heads up. You may have noticed I have arbitrarily set a minimal fwup version in the code that need to be adjusted with regard to the PR in fwup.

**Comment by jeanparpaillon** [comment]
@fhunleth I've identified a bug in the code and just updated the PR: when creating firmware archive, ensure meta.conf.<alg> and meta.conf are the first files in the archive

**Comment by jeanparpaillon** [comment]
@fhunleth same fix pushed to https://github.com/nerves-project/nerves/pull/857

**Comment by fhunleth** [comment]
FYI - I switched the destination branch to `maint-v1.0`. When this functionality gets added, I'd like to get it in 2.0 as well.

**Review by jjcarstens — APPROVED** [review]
So sorry this took so long! Will add to `main` shortly as well

**Comment by jeanparpaillon** [comment]
:+1:

**Pull request merged**
