### PR TITLE
Add example gettext

### PR DESCRIPTION
**Pull request by Theuns-Botha**

### CODE REVIEW

**Comment by mobileoverlord** [comment]
❤️ 💚 💙

**Comment by fhunleth** [comment]
@Theuns-Botha Thanks for contributing this! I suspect that we'd merge this regardless, but if you have a regression test for the language selection piece, that would be helpful.

**Comment by mobileoverlord** [comment]
This is looking really good. It appears that we are going to need to update our CI automation to run `mix gettext.merge priv/gettext` when building the production container?

**Comment by Theuns-Botha** [comment]
That is debatable, I suspect a developer that is working on the UI should actually run this and verify his/her own work. Which would negate the usefulness of running it separately.

**Comment by mobileoverlord** [comment]
Ah I understand, so the po files are checked into git then.

**Comment by Theuns-Botha** [comment]
Correct

**Comment by mobileoverlord** [comment]
Ah! I edited the gitignore only to realize it already had a `/priv/static` entry. can you please force push and I'll merge :)

**Comment by Theuns-Botha** [comment]
I will push when I am back home again(I am at work and the code is on my personal PC)

**Comment by fhunleth** [comment]
No need to do anything. I fixed and merged it manually. Thanks!

**Pull request closed without merging**
