### PR TITLE
Update UI for Product index page

### PR DESCRIPTION
**Pull request by stwf**
Also upgraded font awesome and fix ed issues with the footer not sticking to the page bottom

### CODE REVIEW

**Comment by stwf** [comment]
screen shot 2018-08-25 at 9 43 10 pm

**Comment by fhunleth** [comment]
Looks nice.

Let me make sure that I understand the icons.
The + icon is to create a new product.
The trashcan is to delete a product.
Are the other two "show" and "edit"?

**Comment by stwf** [comment]
They are for firmware, and deployments. There is a tooltip hover thing explaining that, but I know its not the best. I can see the case for little text buttons for that too. Just figured I'd start here, so opinions welcome.

Also different icon choices:
https://fontawesome.com/icons?d=gallery&m=free

**Comment by stwf** [comment]
Clicking on the name, it's a link is the show, and you said to get rid if the edit.

**Comment by fhunleth** [comment]
Sounds good to me. I don't have any better ideas right now for the icons.

**Pull request merged**
