### PR TITLE
Add Changelog and move it to v2.0.0

### PR DESCRIPTION
**Pull request by lawik**

### CODE REVIEW

**Review by oestrich — APPROVED** [review]
:shipit:

I roll up a weekly changelog for SmartRent when I deploy to production, I can take those and bundle them up into a changelog update afterwards

**Comment by lawik** [comment]
Sweet!

PR those here then we all get an eye on what goes into a version I reckon :)

**Comment by lawik** [comment]
Think we should hold this until main actually passes CI :)

**Review by joshk — APPROVED** [review]

**Comment by joshk** [comment]
Once this is merged in, I think we should tag main and tag the docker image as well.

**Pull request merged**
