### PR TITLE
Multiple JITP ca per product

### PR DESCRIPTION
**Pull request by jeanparpaillon**

### CODE REVIEW

**Comment by jeanparpaillon** [comment]
Change jitp>product relation to has_many

Actual relation between jitp and product is has_one. There is no valid
reason for limiting JITP enabled certificate to one per product.

This commit:
* updates Ecto schema
* adds migration to remove unique_index on jitp.product_id

**Comment by fhunleth** [comment]
@jeanparpaillon The "Change jitp>product relation" change seems good to me. Did you mean to include the CircleCI changes? (fwiw, the environment variable additions looked good except for the one pointing to your server).

**Comment by jeanparpaillon** [comment]
@fhunleth sorry, of course CI change was not meant to be included :) I've removed the commit about CI

**Comment by fhunleth** [comment]
No worries. Thanks for the quick fix and for the update!

**Pull request merged**
